import Foundation

// DiscoDrive localization. The language comes from the server (not the system locale), so
// we maintain a simple string table and switch by the active language in AppState.
// Supported languages match the server list: en (default), de, uk, fr, es, ru, sr.
public enum L10n {
    public static let supported = ["en", "de", "uk", "fr", "es", "ru", "sr"]

    // Endonym: each language name is shown in that language itself — do not translate.
    public static let displayName: [String: String] = [
        "en": "English", "de": "Deutsch", "uk": "Українська",
        "fr": "Français", "es": "Español", "ru": "Русский", "sr": "Српски",
    ]

    public static func t(_ key: String, _ lang: String) -> String {
        table[key]?[lang] ?? table[key]?["en"] ?? key
    }

    // key → (lang → text). en is the base / fallback.
    static let table: [String: [String: String]] = [
        "dav.profileSignatureHint": ["en": "If your server signs the profile with a self-signed certificate, the system may show “Not Verified” or “Unverified Profile” during setup. Continue only if you requested this connection in DiscoDrive and recognize the server address. You do not need to disable HTTPS verification or install a root certificate.", "de": "Wenn Ihr Server das Profil mit einem selbstsignierten Zertifikat signiert, kann das System während der Einrichtung „Nicht verifiziert“ oder „Nicht verifiziertes Profil“ anzeigen. Fahren Sie nur fort, wenn Sie diese Verbindung in DiscoDrive angefordert haben und die Serveradresse kennen. Sie müssen weder die HTTPS-Prüfung deaktivieren noch ein Stammzertifikat installieren.", "uk": "Якщо сервер підписує профіль самопідписаним сертифікатом, система може показати «Не перевірено» або «Неперевірений профіль» під час налаштування. Продовжуйте, лише якщо Ви самі запросили це підключення в DiscoDrive та впізнаєте адресу сервера. Вимикати перевірку HTTPS або встановлювати кореневий сертифікат не потрібно.", "fr": "Si votre serveur signe le profil avec un certificat autosigné, le système peut afficher « Non vérifié » ou « Profil non vérifié » pendant la configuration. Continuez uniquement si vous avez demandé cette connexion dans DiscoDrive et reconnaissez l’adresse du serveur. Il n’est pas nécessaire de désactiver la vérification HTTPS ni d’installer un certificat racine.", "es": "Si su servidor firma el perfil con un certificado autofirmado, el sistema puede mostrar «No verificado» o «Perfil no verificado» durante la configuración. Continúe solo si ha solicitado esta conexión en DiscoDrive y reconoce la dirección del servidor. No necesita desactivar la verificación HTTPS ni instalar un certificado raíz.", "ru": "Если сервер подписывает профиль самоподписанным сертификатом, при настройке система может показать «Не проверено» или «Непроверенный профиль». Продолжайте, только если вы сами запросили это подключение в DiscoDrive и узнаёте адрес сервера. Отключать проверку HTTPS или устанавливать корневой сертификат не требуется.", "sr": "Ако сервер потписује профил самопотписаним сертификатом, систем током подешавања може приказати „Није проверено“ или „Непроверен профил“. Наставите само ако сте сами затражили ово повезивање у DiscoDrive-у и препознајете адресу сервера. Није потребно да искључите HTTPS проверу или инсталирате корени сертификат."],
        "dav.automatic": ["en": "Connect without entering passwords", "ru": "Подключить без ввода паролей", "uk": "Підключити без введення паролів", "de": "Ohne Passworteingabe verbinden", "fr": "Connecter sans saisir de mots de passe", "es": "Conectar sin introducir contraseñas", "sr": "Повежите без уноса лозинки"],
        "dav.automaticHint": ["en": "The server must support encrypted setup. Confirm the profile in system Settings; account passwords are filled in automatically.", "de": "Der Server muss die verschlüsselte Einrichtung unterstützen. Bestätigen Sie das Profil in den Systemeinstellungen; Kontopasswörter werden automatisch ausgefüllt.", "uk": "Сервер має підтримувати зашифроване налаштування. Підтвердьте профіль у системних налаштуваннях; паролі облікових записів буде заповнено автоматично.", "fr": "Le serveur doit prendre en charge la configuration chiffrée. Confirmez le profil dans les réglages système ; les mots de passe des comptes sont renseignés automatiquement.", "es": "El servidor debe admitir la configuración cifrada. Confirme el perfil en los ajustes del sistema; las contraseñas de las cuentas se rellenan automáticamente.", "ru": "Сервер должен поддерживать зашифрованную настройку. Подтвердите профиль в системных настройках; пароли учётных записей заполнятся автоматически.", "sr": "Сервер мора подржавати шифровано подешавање. Потврдите профил у системским подешавањима; лозинке налога се попуњавају аутоматски."],
        "dav.automaticInstallHint": ["en": "Open the downloaded profile in system Settings and confirm calendar and contact account setup. You may need your device passcode, but not account passwords. The link expires in 10 minutes.", "ru": "В системных настройках откройте загруженный профиль и подтвердите настройку учётных записей календаря и контактов. Может понадобиться код устройства, но не пароли учётных записей. Ссылка действует 10 минут.", "uk": "У системних налаштуваннях відкрийте завантажений профіль і підтвердьте налаштування облікових записів календаря та контактів. Може знадобитися код пристрою, але не паролі облікових записів. Посилання діє 10 хвилин.", "de": "Öffnen Sie das geladene Profil in den Systemeinstellungen und bestätigen Sie die Einrichtung der Kalender- und Kontaktkonten. Eventuell benötigen Sie den Gerätecode, aber keine Kontopasswörter. Der Link gilt 10 Minuten.", "fr": "Ouvrez le profil téléchargé dans les réglages système et confirmez la configuration des comptes de calendrier et de contacts. Le code de votre appareil peut être demandé, mais pas les mots de passe des comptes. Le lien expire dans 10 minutes.", "es": "Abra el perfil descargado en los ajustes del sistema y confirme la configuración de las cuentas de calendario y contactos. Puede necesitar el código del dispositivo, pero no las contraseñas de las cuentas. El enlace caduca en 10 minutos.", "sr": "Отворите преузети профил у системским подешавањима и потврдите подешавање налога календара и контаката. Можда ће бити потребна шифра уређаја, али не лозинке налога. Веза важи 10 минута."],
        "dav.automaticUnavailable": ["en": "Encrypted setup is not enabled on this server yet. You can use the regular connection method.", "de": "Die verschlüsselte Einrichtung ist auf diesem Server noch nicht aktiviert. Sie können die normale Verbindungsmethode verwenden.", "uk": "Зашифроване налаштування ще не ввімкнено на цьому сервері. Ви можете скористатися звичайним способом підключення.", "fr": "La configuration chiffrée n’est pas encore activée sur ce serveur. Vous pouvez utiliser la méthode de connexion habituelle.", "es": "La configuración cifrada aún no está activada en este servidor. Puede utilizar el método de conexión habitual.", "ru": "На этом сервере ещё не включена зашифрованная настройка. Вы можете воспользоваться обычным способом подключения.", "sr": "Шифровано подешавање још није укључено на овом серверу. Можете користити уобичајени начин повезивања."],
        "dav.retry": ["en": "Try again", "de": "Erneut versuchen", "uk": "Спробувати ще раз", "fr": "Réessayer", "es": "Reintentar", "ru": "Повторить", "sr": "Покушајте поново"],
        "dav.error": ["en": "Could not prepare the connection. Check the server connection and try again.", "de": "Die Verbindung konnte nicht vorbereitet werden. Prüfen Sie die Serververbindung und versuchen Sie es erneut.", "uk": "Не вдалося підготувати підключення. Перевірте з’єднання із сервером і спробуйте ще раз.", "fr": "Impossible de préparer la connexion. Vérifiez la connexion au serveur et réessayez.", "es": "No se pudo preparar la conexión. Compruebe la conexión al servidor e inténtelo de nuevo.", "ru": "Не удалось подготовить подключение. Проверьте соединение с сервером и попробуйте ещё раз.", "sr": "Повезивање није припремљено. Проверите везу са сервером и покушајте поново."],
        "dav.preparing": ["en": "Preparing connection…", "de": "Verbindung wird vorbereitet…", "uk": "Підготовка підключення…", "fr": "Préparation de la connexion…", "es": "Preparando conexión…", "ru": "Подготовка подключения…", "sr": "Припрема повезивања…"],
        "dav.title": ["en": "Calendars and contacts", "de": "Kalender und Kontakte", "uk": "Календарі та контакти", "fr": "Calendriers et contacts", "es": "Calendarios y contactos", "ru": "Календари и контакты", "sr": "Календари и контакти"],
        "dav.calendars": ["en": "Calendars", "de": "Kalender", "uk": "Календарі", "fr": "Calendriers", "es": "Calendarios", "ru": "Календари", "sr": "Календари"],
        "dav.contacts": ["en": "Contacts", "de": "Kontakte", "uk": "Контакти", "fr": "Contacts", "es": "Contactos", "ru": "Контакты", "sr": "Контакти"],
        "dav.prepare": ["en": "Connect with password entry", "de": "Mit Passworteingabe verbinden", "uk": "Підключити з введенням пароля", "fr": "Connecter avec saisie du mot de passe", "es": "Conectar introduciendo la contraseña", "ru": "Подключить с вводом пароля", "sr": "Повежите уз унос лозинке"],
        "dav.disabled": ["en": "Some services are disabled on the server.", "de": "Einige Dienste sind auf dem Server deaktiviert.", "uk": "Деякі служби вимкнено на сервері.", "fr": "Certains services sont désactivés sur le serveur.", "es": "Algunos servicios están desactivados en el servidor.", "ru": "Некоторые службы отключены на сервере.", "sr": "Неке услуге су онемогућене на серверу."],
        "dav.hint": ["en": "Connect DiscoDrive calendars and contacts to the system apps. Confirm account setup in system Settings.", "ru": "Подключите календари и контакты DiscoDrive к системным приложениям. Настройку учётных записей нужно подтвердить в системных настройках.", "uk": "Підключіть календарі та контакти DiscoDrive до системних програм. Налаштування облікових записів потрібно підтвердити в системних налаштуваннях.", "de": "Verbinden Sie DiscoDrive-Kalender und -Kontakte mit den System-Apps. Bestätigen Sie die Kontoeinrichtung in den Systemeinstellungen.", "fr": "Connectez les calendriers et contacts DiscoDrive aux apps système. Confirmez la configuration des comptes dans les réglages système.", "es": "Conecte los calendarios y contactos de DiscoDrive a las apps del sistema. Confirme la configuración de las cuentas en los ajustes del sistema.", "sr": "Повежите DiscoDrive календаре и контакте са системским апликацијама. Потврдите подешавање налога у системским подешавањима."],
        "dav.copyPassword": ["en": "Copy connection password", "de": "Verbindungspasswort kopieren", "uk": "Скопіювати пароль підключення", "fr": "Copier le mot de passe de connexion", "es": "Copiar contraseña de conexión", "ru": "Скопировать пароль подключения", "sr": "Копирајте лозинку за повезивање"],
        "dav.copied": ["en": "Password copied", "de": "Passwort kopiert", "uk": "Пароль скопійовано", "fr": "Mot de passe copié", "es": "Contraseña copiada", "ru": "Пароль скопирован", "sr": "Лозинка је копирана"],
        "dav.install": ["en": "Download setup profile", "ru": "Скачать профиль настройки", "uk": "Завантажити профіль налаштування", "de": "Konfigurationsprofil herunterladen", "fr": "Télécharger le profil de configuration", "es": "Descargar perfil de configuración", "sr": "Преузмите профил подешавања"],
        "dav.installHint": ["en": "Copy the password, download the profile, then open it in system Settings to configure calendar and contact accounts. Paste the password when asked for each selected account. The download link expires in 10 minutes.", "ru": "Скопируйте пароль, скачайте профиль и откройте его в системных настройках для настройки учётных записей календаря и контактов. Вставьте пароль по запросу для каждой выбранной учётной записи. Ссылка на скачивание действует 10 минут.", "uk": "Скопіюйте пароль, завантажте профіль і відкрийте його в системних налаштуваннях для налаштування облікових записів календаря та контактів. Вставте пароль для кожного вибраного облікового запису. Посилання діє 10 хвилин.", "de": "Kopieren Sie das Passwort, laden Sie das Profil herunter und öffnen Sie es in den Systemeinstellungen zur Einrichtung der Kalender- und Kontaktkonten. Fügen Sie das Passwort für jedes ausgewählte Konto ein. Der Link gilt 10 Minuten.", "fr": "Copiez le mot de passe, téléchargez le profil et ouvrez-le dans les réglages système pour configurer les comptes de calendrier et de contacts. Collez le mot de passe pour chaque compte sélectionné. Le lien expire dans 10 minutes.", "es": "Copie la contraseña, descargue el perfil y ábralo en los ajustes del sistema para configurar las cuentas de calendario y contactos. Pegue la contraseña para cada cuenta seleccionada. El enlace caduca en 10 minutos.", "sr": "Копирајте лозинку, преузмите профил и отворите га у системским подешавањима да подесите налоге календара и контаката. Налепите лозинку за сваки изабрани налог. Веза важи 10 минута."],
        "dav.prepareAgain": ["en": "Prepare the connection again to get a new download link. Your existing password will be reused.", "de": "Bereiten Sie die Verbindung erneut vor, um einen neuen Download-Link zu erhalten. Ihr bestehendes Passwort wird wiederverwendet.", "uk": "Підготуйте підключення ще раз, щоб отримати нове посилання. Буде використано наявний пароль.", "fr": "Préparez à nouveau la connexion pour obtenir un nouveau lien. Votre mot de passe existant sera réutilisé.", "es": "Prepare de nuevo la conexión para obtener otro enlace. Se reutilizará su contraseña actual.", "ru": "Подготовьте подключение ещё раз для новой ссылки на скачивание. Будет использован существующий пароль.", "sr": "Поново припремите повезивање за нову везу. Користиће се постојећа лозинка."],
        "dav.revoke": ["en": "Revoke connection password", "de": "Verbindungspasswort widerrufen", "uk": "Відкликати пароль підключення", "fr": "Révoquer le mot de passe de connexion", "es": "Revocar contraseña de conexión", "ru": "Отозвать пароль подключения", "sr": "Опозовите лозинку за повезивање"],
        "dav.revokeHint": ["en": "System calendar and contact synchronization using this password will stop. Remove the installed profile in system Settings if you no longer need it.", "de": "Die Systemsynchronisierung mit diesem Passwort wird beendet. Entfernen Sie das installierte Profil in den Systemeinstellungen, wenn Sie es nicht mehr benötigen.", "uk": "Системна синхронізація з цим паролем зупиниться. Видаліть установлений профіль у системних налаштуваннях, якщо він більше не потрібен.", "fr": "La synchronisation système utilisant ce mot de passe s’arrêtera. Supprimez le profil installé dans les réglages système si vous n’en avez plus besoin.", "es": "Se detendrá la sincronización del sistema que use esta contraseña. Elimine el perfil instalado en los ajustes si ya no lo necesita.", "ru": "Системная синхронизация с этим паролем остановится. Удалите установленный профиль в системных настройках, если он больше не нужен.", "sr": "Системска синхронизација са овом лозинком ће престати. Уклоните инсталирани профил у системским подешавањима ако Вам више није потребан."],
        "dav.independent": ["en": "System accounts keep syncing after you exit or unpair DiscoDrive. Revoke their password here or in the server’s device settings.", "de": "Systemkonten synchronisieren auch nach dem Beenden oder Entkoppeln von DiscoDrive. Widerrufen Sie ihr Passwort hier oder in den Geräteeinstellungen des Servers.", "uk": "Системні облікові записи синхронізуються після виходу або від’єднання DiscoDrive. Відкличте їхній пароль тут або в налаштуваннях пристроїв сервера.", "fr": "Les comptes système continuent la synchronisation après la fermeture ou la dissociation de DiscoDrive. Révoquez leur mot de passe ici ou dans les appareils du serveur.", "es": "Las cuentas del sistema siguen sincronizándose al cerrar o desvincular DiscoDrive. Revoque su contraseña aquí o en los dispositivos del servidor.", "ru": "Системные учётные записи продолжают синхронизацию после выхода или распаривания DiscoDrive. Отозвать их пароль можно здесь или в настройках устройств на сервере.", "sr": "Системски налози настављају синхронизацију после затварања или распаривања DiscoDrive-а. Опозовите лозинку овде или у подешавањима уређаја на серверу."],
        "dav.updateServer": ["en": "Update the DiscoDrive server to enable calendar and contact setup.", "ru": "Обновите сервер DiscoDrive для настройки календарей и контактов.", "uk": "Оновіть сервер DiscoDrive для налаштування календарів і контактів.", "de": "Aktualisieren Sie den DiscoDrive-Server, um Kalender und Kontakte einzurichten.", "fr": "Mettez à jour le serveur DiscoDrive pour configurer les calendriers et contacts.", "es": "Actualice el servidor DiscoDrive para configurar calendarios y contactos.", "sr": "Ажурирајте DiscoDrive сервер да подесите календаре и контакте."],
        "recovery.trash": ["en": "Trash", "de": "Papierkorb", "uk": "Кошик", "fr": "Corbeille", "es": "Papelera", "ru": "Корзина", "sr": "Отпад"],
        "recovery.versions": ["en": "Version history", "de": "Versionsverlauf", "uk": "Історія версій", "fr": "Historique des versions", "es": "Historial de versiones", "ru": "История версий", "sr": "Историја верзија"],
        "recovery.version": ["en": "Version", "de": "Version", "uk": "Версія", "fr": "Version", "es": "Versión", "ru": "Версия", "sr": "Верзија"],
        "recovery.restore": ["en": "Restore", "de": "Wiederherstellen", "uk": "Відновити", "fr": "Restaurer", "es": "Restaurar", "ru": "Восстановить", "sr": "Вратите"],
        "recovery.restored": ["en": "Restored on the server.", "de": "Auf dem Server wiederhergestellt.", "uk": "Відновлено на сервері.", "fr": "Restauré sur le serveur.", "es": "Restaurado en el servidor.", "ru": "Восстановлено на сервере.", "sr": "Враћено на серверу."],
        "recovery.purge": ["en": "Delete permanently", "de": "Endgültig löschen", "uk": "Видалити назавжди", "fr": "Supprimer définitivement", "es": "Eliminar definitivamente", "ru": "Удалить навсегда", "sr": "Трајно избришите"],
        "recovery.empty": ["en": "Empty trash…", "de": "Papierkorb leeren…", "uk": "Очистити кошик…", "fr": "Vider la corbeille…", "es": "Vaciar papelera…", "ru": "Очистить корзину…", "sr": "Испразните отпад…"],
        "recovery.emptyTrash": ["en": "Trash is empty.", "de": "Der Papierkorb ist leer.", "uk": "Кошик порожній.", "fr": "La corbeille est vide.", "es": "La papelera está vacía.", "ru": "Корзина пуста.", "sr": "Отпад је празан."],
        "recovery.emptyVersions": ["en": "No saved versions.", "de": "Keine gespeicherten Versionen.", "uk": "Немає збережених версій.", "fr": "Aucune version enregistrée.", "es": "No hay versiones guardadas.", "ru": "Сохранённых версий нет.", "sr": "Нема сачуваних верзија."],
        "recovery.purgeWarning": ["en": "This permanently removes the selected items and their history from the server. This cannot be undone.", "de": "Die ausgewählten Elemente und ihr Verlauf werden endgültig vom Server gelöscht. Dies kann nicht rückgängig gemacht werden.", "uk": "Вибрані елементи та їхню історію буде назавжди видалено із сервера. Цю дію неможливо скасувати.", "fr": "Les éléments sélectionnés et leur historique seront définitivement supprimés du serveur. Cette action est irréversible.", "es": "Los elementos seleccionados y su historial se eliminarán del servidor permanentemente. Esta acción no se puede deshacer.", "ru": "Выбранные элементы и их история будут удалены с сервера навсегда. Это действие нельзя отменить.", "sr": "Изабране ставке и њихова историја биће трајно избрисане са сервера. Ова радња се не може поништити."],
        "recovery.versionHint": ["en": "Restoring replaces the current contents on all synced devices. The previous contents remain in version history.", "de": "Die Wiederherstellung ersetzt den aktuellen Inhalt auf allen synchronisierten Geräten. Der vorherige Inhalt bleibt im Versionsverlauf erhalten.", "uk": "Відновлення замінює поточний вміст на всіх синхронізованих пристроях. Попередній вміст залишається в історії версій.", "fr": "La restauration remplace le contenu actuel sur tous les appareils synchronisés. Le contenu précédent reste dans l’historique.", "es": "La restauración reemplaza el contenido actual en todos los dispositivos sincronizados. El contenido anterior permanece en el historial.", "ru": "Восстановление заменяет содержимое на всех синхронизируемых устройствах. Предыдущее содержимое остаётся в истории версий.", "sr": "Враћање замењује тренутни садржај на свим синхронизованим уређајима. Претходни садржај остаје у историји верзија."],
        "recovery.conflict": ["en": "Saved conflicting version", "de": "Gespeicherte Konfliktversion", "uk": "Збережена конфліктна версія", "fr": "Version en conflit conservée", "es": "Versión en conflicto guardada", "ru": "Сохранённая конфликтная версия", "sr": "Сачувана конфликтна верзија"],
        "activity.title": ["en": "Sync activity", "de": "Synchronisierungsaktivität", "uk": "Перебіг синхронізації", "fr": "Activité de synchronisation", "es": "Actividad de sincronización", "ru": "Ход синхронизации", "sr": "Ток синхронизације"],
        "activity.pull": ["en": "Downloading", "de": "Herunterladen", "uk": "Завантаження", "fr": "Téléchargement", "es": "Descargando", "ru": "Скачивание", "sr": "Преузимање"],
        "activity.push": ["en": "Uploading", "de": "Hochladen", "uk": "Вивантаження", "fr": "Envoi", "es": "Subiendo", "ru": "Отправка", "sr": "Отпремање"],
        "activity.scan": ["en": "Checking local files", "de": "Lokale Dateien werden geprüft", "uk": "Перевірка локальних файлів", "fr": "Vérification des fichiers locaux", "es": "Comprobando archivos locales", "ru": "Проверка локальных файлов", "sr": "Провера локалних датотека"],
        "activity.completed": ["en": "Completed operations", "de": "Abgeschlossene Vorgänge", "uk": "Завершені операції", "fr": "Opérations terminées", "es": "Operaciones completadas", "ru": "Завершено операций", "sr": "Завршене операције"],
        "activity.errors": ["en": "Recent errors", "de": "Letzte Fehler", "uk": "Останні помилки", "fr": "Erreurs récentes", "es": "Errores recientes", "ru": "Последние ошибки", "sr": "Недавне грешке"],
        "activity.empty": ["en": "No operations in this session yet.", "de": "Noch keine Vorgänge in dieser Sitzung.", "uk": "У цьому сеансі ще не було операцій.", "fr": "Aucune opération dans cette session.", "es": "Aún no hay operaciones en esta sesión.", "ru": "В этом сеансе операций ещё не было.", "sr": "У овој сесији још нема операција."],
        "activity.hint": ["en": "Activity is kept only during the current sync session. Failed operations are retried by synchronization.", "de": "Die Aktivität wird nur während der aktuellen Synchronisierungssitzung gespeichert. Fehlgeschlagene Vorgänge werden erneut versucht.", "uk": "Дані зберігаються лише протягом поточного сеансу синхронізації. Невдалі операції повторюються.", "fr": "L’activité est conservée uniquement pendant la session en cours. Les opérations échouées sont réessayées.", "es": "La actividad se conserva solo durante la sesión actual. La sincronización reintenta las operaciones fallidas.", "ru": "Сведения хранятся только в текущем сеансе синхронизации. Неудачные операции синхронизация повторит.", "sr": "Активност се чува само током текуће сесије синхронизације. Неуспеле операције се понављају."],

        "share.title": [
            "en": "Share",
            "de": "Teilen",
            "uk": "Поділитися",
            "fr": "Partager",
            "es": "Compartir",
            "ru": "Поделиться",
            "sr": "Поделите",
        ],
        "share.method": [
            "en": "Share via",
            "de": "Teilen über",
            "uk": "Спосіб доступу",
            "fr": "Partager via",
            "es": "Compartir mediante",
            "ru": "Способ доступа",
            "sr": "Начин дељења",
        ],
        "share.link": [
            "en": "Link",
            "de": "Link",
            "uk": "Посилання",
            "fr": "Lien",
            "es": "Enlace",
            "ru": "Ссылка",
            "sr": "Веза",
        ],
        "share.user": [
            "en": "User",
            "de": "Benutzer",
            "uk": "Користувач",
            "fr": "Utilisateur",
            "es": "Usuario",
            "ru": "Пользователь",
            "sr": "Корисник",
        ],
        "share.email": [
            "en": "Email address",
            "de": "E-Mail-Adresse",
            "uk": "Електронна пошта",
            "fr": "Adresse e-mail",
            "es": "Correo electrónico",
            "ru": "Электронная почта",
            "sr": "Имејл адреса",
        ],
        "share.expiry": [
            "en": "Expires after",
            "de": "Gültig für",
            "uk": "Термін дії",
            "fr": "Durée de validité",
            "es": "Caducidad",
            "ru": "Срок действия",
            "sr": "Рок важења",
        ],
        "share.forever": [
            "en": "No expiry",
            "de": "Unbegrenzt",
            "uk": "Без обмеження",
            "fr": "Sans expiration",
            "es": "Sin caducidad",
            "ru": "Без ограничения",
            "sr": "Без ограничења",
        ],
        "share.day": [
            "en": "1 day",
            "de": "1 Tag",
            "uk": "1 день",
            "fr": "1 jour",
            "es": "1 día",
            "ru": "1 день",
            "sr": "1 дан",
        ],
        "share.week": [
            "en": "7 days",
            "de": "7 Tage",
            "uk": "7 днів",
            "fr": "7 jours",
            "es": "7 días",
            "ru": "7 дней",
            "sr": "7 дана",
        ],
        "share.month": [
            "en": "30 days",
            "de": "30 Tage",
            "uk": "30 днів",
            "fr": "30 jours",
            "es": "30 días",
            "ru": "30 дней",
            "sr": "30 дана",
        ],
        "share.create": [
            "en": "Create link",
            "de": "Link erstellen",
            "uk": "Створити посилання",
            "fr": "Créer un lien",
            "es": "Crear enlace",
            "ru": "Создать ссылку",
            "sr": "Направите везу",
        ],
        "share.grant": [
            "en": "Grant access",
            "de": "Zugriff gewähren",
            "uk": "Надати доступ",
            "fr": "Accorder l’accès",
            "es": "Conceder acceso",
            "ru": "Предоставить доступ",
            "sr": "Одобрите приступ",
        ],
        "share.readOnly": [
            "en": "Recipients can view and download. Anyone with a link can use it until it expires or you revoke it.",
            "de": "Empfänger können ansehen und herunterladen. Jeder mit dem Link kann ihn bis zum Ablauf oder Widerruf nutzen.",
            "uk": "Одержувачі можуть переглядати й завантажувати. Посилання доступне всім, хто його має, до завершення терміну або відкликання.",
            "fr": "Les destinataires peuvent consulter et télécharger. Toute personne ayant le lien peut l’utiliser jusqu’à son expiration ou sa révocation.",
            "es": "Los destinatarios pueden ver y descargar. Cualquier persona con el enlace puede usarlo hasta que caduque o se revoque.",
            "ru": "Получатели могут просматривать и скачивать. Ссылкой может воспользоваться любой, у кого она есть, до истечения срока или отзыва доступа.",
            "sr": "Примаоци могу да прегледају и преузимају. Свако ко има везу може је користити до истека или опозива.",
        ],
        "share.send": [
            "en": "Share link",
            "de": "Link teilen",
            "uk": "Поділитися посиланням",
            "fr": "Partager le lien",
            "es": "Compartir enlace",
            "ru": "Отправить ссылку",
            "sr": "Поделите везу",
        ],
        "share.copy": [
            "en": "Copy link",
            "de": "Link kopieren",
            "uk": "Копіювати посилання",
            "fr": "Copier le lien",
            "es": "Copiar enlace",
            "ru": "Скопировать ссылку",
            "sr": "Копирајте везу",
        ],
        "share.empty": [
            "en": "No shared access",
            "de": "Kein geteilter Zugriff",
            "uk": "Спільного доступу немає",
            "fr": "Aucun accès partagé",
            "es": "Sin acceso compartido",
            "ru": "Общий доступ не предоставлен",
            "sr": "Нема дељеног приступа",
        ],
        "share.revoke": [
            "en": "Revoke access",
            "de": "Zugriff widerrufen",
            "uk": "Відкликати доступ",
            "fr": "Révoquer l’accès",
            "es": "Revocar acceso",
            "ru": "Отозвать доступ",
            "sr": "Опозовите приступ",
        ],
        "share.existing": [
            "en": "Shared access",
            "de": "Geteilter Zugriff",
            "uk": "Спільний доступ",
            "fr": "Accès partagé",
            "es": "Acceso compartido",
            "ru": "Общий доступ",
            "sr": "Дељени приступ",
        ],
        "diagnostics.title": [
            "en": "Diagnostics",
            "de": "Diagnose",
            "uk": "Діагностика",
            "fr": "Diagnostic",
            "es": "Diagnóstico",
            "ru": "Диагностика",
            "sr": "Дијагностика",
        ],
        "diagnostics.enable": [
            "en": "Save sync logs",
            "de": "Sync-Protokolle speichern",
            "uk": "Зберігати журнали синхронізації",
            "fr": "Enregistrer les journaux de synchronisation",
            "es": "Guardar registros de sincronización",
            "ru": "Сохранять журнал синхронизации",
            "sr": "Чувајте дневник синхронизације",
        ],
        "diagnostics.export": [
            "en": "Share log",
            "de": "Protokoll teilen",
            "uk": "Поділитися журналом",
            "fr": "Partager le journal",
            "es": "Compartir registro",
            "ru": "Поделиться журналом",
            "sr": "Поделите дневник",
        ],
        "diagnostics.failed": [
            "en": "The log could not be opened. Please check available storage.",
            "de": "Das Protokoll konnte nicht geöffnet werden. Prüfen Sie den freien Speicher.",
            "uk": "Не вдалося відкрити журнал. Перевірте вільне місце.",
            "fr": "Impossible d’ouvrir le journal. Vérifiez l’espace disponible.",
            "es": "No se pudo abrir el registro. Compruebe el espacio disponible.",
            "ru": "Не удалось открыть журнал. Проверьте свободное место.",
            "sr": "Дневник није отворен. Проверите слободан простор.",
        ],
        "diagnostics.hint": [
            "en": "Off by default. Logs are saved in On My iPhone/iPad → DiscoDrive → Logs (up to 4 MB). They contain file paths, timings and errors, without passwords or tokens. Turning this off stops writing; existing logs remain.",
            "de": "Standardmäßig aus. Protokolle liegen unter Auf meinem iPhone/iPad → DiscoDrive → Logs (bis zu 4 MB). Sie enthalten Dateipfade, Zeiten und Fehler, keine Passwörter oder Tokens. Ausschalten beendet die Aufzeichnung; vorhandene Protokolle bleiben.",
            "uk": "Типово вимкнено. Журнали зберігаються в На моєму iPhone/iPad → DiscoDrive → Logs (до 4 МБ). Вони містять шляхи, час і помилки, без паролів і токенів. Вимкнення зупиняє запис; наявні журнали залишаються.",
            "fr": "Désactivé par défaut. Journaux dans Sur mon iPhone/iPad → DiscoDrive → Logs (4 Mo maximum). Ils contiennent les chemins, durées et erreurs, sans mots de passe ni jetons. La désactivation arrête l’écriture et conserve les journaux existants.",
            "es": "Desactivado de forma predeterminada. Registros en En mi iPhone/iPad → DiscoDrive → Logs (hasta 4 MB). Incluyen rutas, tiempos y errores, sin contraseñas ni tokens. Al desactivar se detiene la escritura; los registros existentes permanecen.",
            "ru": "По умолчанию выключено. Журналы сохраняются в «На моём iPhone/iPad → DiscoDrive → Logs» (до 4 МБ). В них есть пути файлов, время операций и ошибки, без паролей и токенов. Выключение останавливает запись; прежние журналы остаются.",
            "sr": "Подразумевано искључено. Дневници су у На мом iPhone/iPad → DiscoDrive → Logs (до 4 MB). Садрже путање, трајања и грешке, без лозинки и токена. Искључивање зауставља писање; постојећи дневници остају.",
        ],
        "ios.files.evicted": [
            "en": "Local copy removed. The file remains on the server.",
            "de": "Lokale Kopie entfernt. Die Datei bleibt auf dem Server.",
            "uk": "Локальну копію видалено. Файл залишається на сервері.",
            "fr": "Copie locale supprimée. Le fichier reste sur le serveur.",
            "es": "Copia local eliminada. El archivo permanece en el servidor.",
            "ru": "Локальная копия удалена. Файл остался на сервере.",
            "sr": "Локална копија је уклоњена. Датотека остаје на серверу.",
        ],
        "ios.files.evictHint": [
            "en": "Remove the downloaded copy from this device. Unsaved changes must finish syncing first.",
            "de": "Entfernen Sie die geladene Kopie von diesem Gerät. Änderungen müssen zuvor synchronisiert werden.",
            "uk": "Видаліть завантажену копію з пристрою. Спочатку має завершитися синхронізація змін.",
            "fr": "Supprimez la copie téléchargée sur cet appareil. Les modifications doivent d’abord être synchronisées.",
            "es": "Elimine la copia descargada del dispositivo. Los cambios deben sincronizarse primero.",
            "ru": "Удаление скачанной копии с этого устройства. Если есть несохранённые изменения, сначала дождитесь их синхронизации.",
            "sr": "Уклоните преузету копију са уређаја. Измене прво морају да се синхронизују.",
        ],
        "ios.files.authenticate": [
            "en": "Open DiscoDrive to restore your connection. If this is a vault, unlock it in the app, then return to Files.",
            "de": "Öffnen Sie DiscoDrive, um die Verbindung wiederherzustellen. Entsperren Sie einen Tresor in der App und kehren Sie anschließend zu Dateien zurück.",
            "uk": "Відкрийте DiscoDrive, щоб відновити підключення. Якщо це сейф, розблокуйте його в застосунку й поверніться до Файлів.",
            "fr": "Ouvrez DiscoDrive pour rétablir la connexion. S’il s’agit d’un coffre, déverrouillez-le dans l’application, puis revenez à Fichiers.",
            "es": "Abra DiscoDrive para restablecer la conexión. Si es una caja fuerte, desbloquéela en la aplicación y vuelva a Archivos.",
            "ru": "Откройте DiscoDrive, чтобы восстановить подключение. Если это сейф, откройте его в приложении, затем вернитесь в «Файлы».",
            "sr": "Отворите DiscoDrive да бисте обновили везу. Ако је ово сеф, откључајте га у апликацији, па се вратите у Датотеке.",
        ],
        "ios.files.lockAll": [
            "en": "Lock all vaults", "de": "Alle Tresore sperren", "uk": "Заблокувати всі сейфи",
            "fr": "Verrouiller tous les coffres", "es": "Bloquear todas las cajas fuertes",
            "ru": "Закрыть все сейфы", "sr": "Закључајте све сефове",
        ],
        "ios.files.title": [
            "en": "Files integration",
            "de": "Integration in Dateien",
            "uk": "Інтеграція з Файлами",
            "fr": "Intégration à Fichiers",
            "es": "Integración con Archivos",
            "ru": "Интеграция с «Файлами»",
            "sr": "Интеграција са Датотекама",
        ],
        "ios.files.connected": [
            "en": "DiscoDrive is connected",
            "de": "DiscoDrive ist verbunden",
            "uk": "DiscoDrive підключено",
            "fr": "DiscoDrive est connecté",
            "es": "DiscoDrive está conectado",
            "ru": "DiscoDrive подключён",
            "sr": "DiscoDrive је повезан",
        ],
        "ios.files.disconnected": [
            "en": "DiscoDrive is not connected",
            "de": "DiscoDrive ist nicht verbunden",
            "uk": "DiscoDrive не підключено",
            "fr": "DiscoDrive n’est pas connecté",
            "es": "DiscoDrive no está conectado",
            "ru": "DiscoDrive не подключён",
            "sr": "DiscoDrive није повезан",
        ],
        "ios.files.connect": [
            "en": "Reconnect to Files",
            "de": "Erneut mit Dateien verbinden",
            "uk": "Підключити до Файлів знову",
            "fr": "Reconnecter à Fichiers",
            "es": "Reconectar con Archivos",
            "ru": "Подключить к «Файлам» заново",
            "sr": "Поново повежите са Датотекама",
        ],
        "ios.files.hint": [
            "en": "In Files, open Browse → Edit and enable DiscoDrive. Files download when opened. Open vaults in the DiscoDrive app.",
            "de": "Öffnen Sie in Dateien „Durchsuchen → Bearbeiten“ und aktivieren Sie DiscoDrive. Dateien werden beim Öffnen geladen. Öffnen Sie Tresore in der DiscoDrive-App.",
            "uk": "У Файлах відкрийте «Огляд → Редагувати» та ввімкніть DiscoDrive. Файли завантажуються під час відкриття. Відкривайте сейфи в застосунку DiscoDrive.",
            "fr": "Dans Fichiers, ouvrez Explorer → Modifier et activez DiscoDrive. Les fichiers se téléchargent à l’ouverture. Ouvrez les coffres dans l’application DiscoDrive.",
            "es": "En Archivos, abra Explorar → Editar y active DiscoDrive. Los archivos se descargan al abrirlos. Abra las cajas fuertes en la aplicación DiscoDrive.",
            "ru": "В «Файлах» откройте «Обзор → Править» и включите DiscoDrive. Файлы скачиваются при открытии. Открывайте сейфы в приложении DiscoDrive.",
            "sr": "У Датотекама отворите Преглед → Уреди и укључите DiscoDrive. Датотеке се преузимају при отварању. Сефове отварајте у апликацији DiscoDrive.",
        ],
        "ios.sync.folder": [
            "en": "Local folder",
            "de": "Lokaler Ordner",
            "uk": "Локальна папка",
            "fr": "Dossier local",
            "es": "Carpeta local",
            "ru": "Папка на устройстве",
            "sr": "Локална фасцикла",
        ],
        "ios.sync.hint": [
            "en": "A complete two-way copy of the folder selected on your server, stored in DiscoDrive → Sync on this device. Existing files are preserved in Sync Backups before the first sync. Sync runs while the app is open and when iOS grants background time.",
            "de": "Eine vollständige Kopie des auf Ihrem Server gewählten Ordners in DiscoDrive → Sync auf diesem Gerät. Änderungen werden in beide Richtungen übertragen. Vor der ersten Synchronisierung werden vorhandene Dateien in Sync Backups gesichert. Die Synchronisierung läuft bei geöffneter App und wenn iOS Hintergrundzeit gewährt.",
            "uk": "Повна двостороння копія вибраної на сервері папки в DiscoDrive → Sync на цьому пристрої. Перед першою синхронізацією наявні файли зберігаються в Sync Backups. Синхронізація працює у відкритому застосунку та коли iOS надає фоновий час.",
            "fr": "Une copie complète et bidirectionnelle du dossier choisi sur votre serveur, dans DiscoDrive → Sync sur cet appareil. Les fichiers existants sont conservés dans Sync Backups avant la première synchronisation. La synchronisation fonctionne avec l’application ouverte et lorsque iOS autorise du temps en arrière-plan.",
            "es": "Copia completa y bidireccional de la carpeta seleccionada en su servidor, en DiscoDrive → Sync de este dispositivo. Los archivos existentes se guardan en Sync Backups antes de la primera sincronización. Funciona con la aplicación abierta y cuando iOS permite tiempo en segundo plano.",
            "ru": "Полная двусторонняя копия выбранной на сервере папки в DiscoDrive → Sync на этом устройстве. Перед первым запуском существующие файлы сохраняются в Sync Backups. Синхронизация работает при открытом приложении и когда iOS выделяет время в фоне.",
            "sr": "Потпуна двосмерна копија фасцикле изабране на серверу, у DiscoDrive → Sync на овом уређају. Постојеће датотеке се чувају у Sync Backups пре прве синхронизације. Синхронизација ради док је апликација отворена и када iOS дозволи рад у позадини.",
        ],
        "fullSync.bulkDelete": [
            "en": "Synchronization paused because many local files disappeared. Check that your disk and folder are available before confirming deletion.",
            "ru": "Синхронизация приостановлена: исчезло много локальных файлов. Перед подтверждением удаления проверьте, доступны ли диск и папка.",
            "uk": "Синхронізацію призупинено: зникло багато локальних файлів. Перед підтвердженням видалення перевірте доступність диска та папки.",
            "fr": "Synchronisation suspendue : de nombreux fichiers locaux ont disparu. Vérifiez que le disque et le dossier sont accessibles avant de confirmer la suppression.",
            "es": "Sincronización pausada: han desaparecido muchos archivos locales. Compruebe que el disco y la carpeta estén disponibles antes de confirmar la eliminación.",
            "sr": "Синхронизација је паузирана: нестало је много локалних датотека. Пре потврде брисања проверите да ли су диск и фасцикла доступни.",
            "de": "Synchronisierung angehalten: Viele lokale Dateien fehlen. Prüfen Sie vor der Löschbestätigung, ob Laufwerk und Ordner verfügbar sind.",
        ],
        "fullSync.confirmDelete": [
            "en": "Confirm deletions…",
            "ru": "Подтвердить удаления…",
            "uk": "Підтвердити видалення…",
            "fr": "Confirmer les suppressions…",
            "es": "Confirmar eliminaciones…",
            "sr": "Потврдите брисања…",
            "de": "Löschungen bestätigen…",
        ],
        "fullSync.deleteWarning": [
            "en": "Files missing from the local folder will also be deleted on the server and other synced devices. Continue only if you deleted them intentionally.",
            "ru": "Файлы, отсутствующие в локальной папке, будут удалены также на сервере и других синхронизируемых устройствах. Продолжайте, только если вы удалили их намеренно.",
            "uk": "Файли, відсутні в локальній папці, також буде видалено на сервері та інших синхронізованих пристроях. Продовжуйте, лише якщо ви видалили їх навмисно.",
            "fr": "Les fichiers absents du dossier local seront aussi supprimés du serveur et des autres appareils synchronisés. Continuez uniquement si vous les avez supprimés volontairement.",
            "es": "Los archivos ausentes de la carpeta local también se eliminarán del servidor y otros dispositivos sincronizados. Continúe solo si los eliminó intencionadamente.",
            "sr": "Датотеке које недостају у локалној фасцикли биће обрисане и са сервера и других синхронизованих уређаја. Наставите само ако сте их намерно обрисали.",
            "de": "Lokal fehlende Dateien werden auch auf dem Server und anderen synchronisierten Geräten gelöscht. Fahren Sie nur fort, wenn Sie die Dateien absichtlich gelöscht haben.",
        ],
        "fullSync.title": [
            "en": "Folder synchronization",
            "ru": "Синхронизация папки",
            "uk": "Синхронізація папки",
            "fr": "Synchronisation de dossier",
            "es": "Sincronización de carpeta",
            "sr": "Синхронизација фасцикле",
            "de": "Ordnersynchronisierung",
        ],
        "fullSync.description": [
            "en": "Keeps complete local copies and syncs changes in both directions while DiscoDrive is running. The server selects the folder; when its folder restriction is off, the entire storage is synced.",
            "ru": "Хранит полные копии файлов и синхронизирует изменения в обе стороны, пока работает DiscoDrive. Папка выбирается на сервере; если ограничение одной папкой выключено, синхронизируется всё хранилище.",
            "uk": "Зберігає повні копії файлів і синхронізує зміни в обидва боки, поки працює DiscoDrive. Папка вибирається на сервері; без обмеження однією папкою синхронізується все сховище.",
            "fr": "Conserve des copies complètes et synchronise les modifications dans les deux sens lorsque DiscoDrive fonctionne. Le dossier est choisi sur le serveur ; sans restriction de dossier, tout le stockage est synchronisé.",
            "es": "Guarda copias completas y sincroniza los cambios en ambos sentidos mientras DiscoDrive está abierto. La carpeta se elige en el servidor; sin la restricción de carpeta, se sincroniza todo el almacenamiento.",
            "sr": "Чува потпуне копије и синхронизује измене у оба смера док DiscoDrive ради. Фасцикла се бира на серверу; без ограничења на једну фасциклу синхронизује се цело складиште.",
            "de": "Speichert vollständige Kopien und synchronisiert Änderungen in beide Richtungen, solange DiscoDrive läuft. Der Ordner wird auf dem Server gewählt; ohne Ordnerbeschränkung wird der gesamte Speicher synchronisiert.",
        ],
        "fullSync.noFolder": [
            "en": "No local folder selected",
            "ru": "Локальная папка не выбрана",
            "uk": "Локальну папку не вибрано",
            "fr": "Aucun dossier local sélectionné",
            "es": "No se ha seleccionado una carpeta local",
            "sr": "Локална фасцикла није изабрана",
            "de": "Kein lokaler Ordner ausgewählt",
        ],
        "fullSync.choose": [
            "en": "Choose folder…",
            "ru": "Выбрать папку…",
            "uk": "Вибрати папку…",
            "fr": "Choisir un dossier…",
            "es": "Elegir carpeta…",
            "sr": "Изаберите фасциклу…",
            "de": "Ordner auswählen…",
        ],
        "fullSync.chooseHint": [
            "en": "Choose a dedicated folder for a complete local copy of your server files.",
            "ru": "Выберите отдельную папку для полной локальной копии файлов с сервера.",
            "uk": "Виберіть окрему папку для повної локальної копії файлів із сервера.",
            "fr": "Choisissez un dossier dédié à la copie locale complète des fichiers du serveur.",
            "es": "Elija una carpeta dedicada a la copia local completa de los archivos del servidor.",
            "sr": "Изаберите засебну фасциклу за потпуну локалну копију датотека са сервера.",
            "de": "Wählen Sie einen eigenen Ordner für die vollständige lokale Kopie Ihrer Serverdateien.",
        ],
        "fullSync.enable": [
            "en": "Enable synchronization",
            "ru": "Включить синхронизацию",
            "uk": "Увімкнути синхронізацію",
            "fr": "Activer la synchronisation",
            "es": "Activar la sincronización",
            "sr": "Укључите синхронизацију",
            "de": "Synchronisierung aktivieren",
        ],
        "fullSync.stopped": [
            "en": "Synchronization is off",
            "ru": "Синхронизация выключена",
            "uk": "Синхронізацію вимкнено",
            "fr": "Synchronisation désactivée",
            "es": "Sincronización desactivada",
            "sr": "Синхронизација је искључена",
            "de": "Synchronisierung ausgeschaltet",
        ],
        "fullSync.preparing": [
            "en": "Saving the previous contents…",
            "ru": "Сохранение прежнего содержимого…",
            "uk": "Збереження попереднього вмісту…",
            "fr": "Sauvegarde du contenu précédent…",
            "es": "Guardando el contenido anterior…",
            "sr": "Чување претходног садржаја…",
            "de": "Bisherige Inhalte werden gesichert…",
        ],
        "fullSync.syncing": [
            "en": "Synchronizing…",
            "ru": "Синхронизация…",
            "uk": "Синхронізація…",
            "fr": "Synchronisation…",
            "es": "Sincronizando…",
            "sr": "Синхронизација…",
            "de": "Synchronisierung läuft…",
        ],
        "fullSync.ready": [
            "en": "Up to date",
            "ru": "Все изменения синхронизированы",
            "uk": "Усі зміни синхронізовано",
            "fr": "À jour",
            "es": "Actualizado",
            "sr": "Све измене су синхронизоване",
            "de": "Auf dem neuesten Stand",
        ],
        "fullSync.error": [
            "en": "Synchronization could not complete. Check the connection and folder access, then switch synchronization off and on to retry.",
            "ru": "Не удалось завершить синхронизацию. Проверьте соединение и доступ к папке, затем выключите и включите синхронизацию для повтора.",
            "uk": "Не вдалося завершити синхронізацію. Перевірте з’єднання та доступ до папки, потім вимкніть і увімкніть синхронізацію для повтору.",
            "fr": "La synchronisation n’a pas pu se terminer. Vérifiez la connexion et l’accès au dossier, puis désactivez et réactivez la synchronisation.",
            "es": "No se pudo completar la sincronización. Compruebe la conexión y el acceso a la carpeta, luego desactive y active la sincronización para reintentar.",
            "sr": "Синхронизација није завршена. Проверите везу и приступ фасцикли, затим искључите и укључите синхронизацију да бисте покушали поново.",
            "de": "Die Synchronisierung konnte nicht abgeschlossen werden. Prüfen Sie Verbindung und Ordnerzugriff und schalten Sie die Synchronisierung aus und wieder ein.",
        ],
        "fullSync.accessError": [
            "en": "Folder access is unavailable. Switch synchronization off and choose the folder again.",
            "ru": "Доступ к папке недоступен. Выключите синхронизацию и выберите папку заново.",
            "uk": "Немає доступу до папки. Вимкніть синхронізацію та виберіть папку знову.",
            "fr": "L’accès au dossier est indisponible. Désactivez la synchronisation et choisissez à nouveau le dossier.",
            "es": "No se puede acceder a la carpeta. Desactive la sincronización y vuelva a elegirla.",
            "sr": "Приступ фасцикли није доступан. Искључите синхронизацију и поново изаберите фасциклу.",
            "de": "Der Ordnerzugriff ist nicht verfügbar. Schalten Sie die Synchronisierung aus und wählen Sie den Ordner erneut.",
        ],
        "fullSync.folderError": [
            "en": "Choose a dedicated folder outside cloud storage and application data.",
            "ru": "Выберите отдельную папку вне облачных дисков и данных приложения.",
            "uk": "Виберіть окрему папку поза хмарними дисками та даними застосунку.",
            "fr": "Choisissez un dossier dédié en dehors des disques cloud et des données de l’application.",
            "es": "Elija una carpeta dedicada fuera de las unidades en la nube y los datos de la aplicación.",
            "sr": "Изаберите засебну фасциклу изван облачних дискова и података апликације.",
            "de": "Wählen Sie einen eigenen Ordner außerhalb von Cloud-Laufwerken und Anwendungsdaten.",
        ],
        "fullSync.backup": [
            "en": "Show previous files",
            "ru": "Показать прежние файлы",
            "uk": "Показати попередні файли",
            "fr": "Afficher les anciens fichiers",
            "es": "Mostrar archivos anteriores",
            "sr": "Прикажи претходне датотеке",
            "de": "Bisherige Dateien anzeigen",
        ],
        "fullSync.backupHint": [
            "en": "On first sync, existing local files are saved separately and the server copy is downloaded. Later changes and deletions sync in both directions.",
            "ru": "При первом запуске прежние локальные файлы сохраняются отдельно, затем скачивается серверная копия. После этого изменения и удаления синхронизируются в обе стороны.",
            "uk": "Під час першого запуску попередні локальні файли зберігаються окремо, потім завантажується серверна копія. Надалі зміни та видалення синхронізуються в обидва боки.",
            "fr": "À la première synchronisation, les fichiers locaux existants sont sauvegardés séparément, puis la copie du serveur est téléchargée. Ensuite, modifications et suppressions sont synchronisées dans les deux sens.",
            "es": "En la primera sincronización, los archivos locales existentes se guardan aparte y se descarga la copia del servidor. Después, los cambios y las eliminaciones se sincronizan en ambos sentidos.",
            "sr": "При првој синхронизацији постојеће локалне датотеке чувају се одвојено, а затим се преузима копија са сервера. Потом се измене и брисања синхронизују у оба смера.",
            "de": "Bei der ersten Synchronisierung werden vorhandene lokale Dateien separat gesichert und die Serverkopie heruntergeladen. Danach werden Änderungen und Löschungen in beide Richtungen synchronisiert.",
        ],
        "finder.openApp": [
            "en": "Open DiscoDrive",
            "ru": "Открыть DiscoDrive",
            "uk": "Відкрити DiscoDrive",
            "fr": "Ouvrir DiscoDrive",
            "es": "Abrir DiscoDrive",
            "sr": "Отвори DiscoDrive",
            "de": "DiscoDrive öffnen",
        ],
        "finder.signIn": [
            "en": "Continue in DiscoDrive to restore access to your files.",
            "ru": "Продолжите в DiscoDrive, чтобы восстановить доступ к вашим файлам.",
            "uk": "Продовжте в DiscoDrive, щоб відновити доступ до ваших файлів.",
            "fr": "Continuez dans DiscoDrive pour rétablir l’accès à vos fichiers.",
            "es": "Continúe en DiscoDrive para recuperar el acceso a sus archivos.",
            "sr": "Наставите у DiscoDrive да бисте вратили приступ вашим датотекама.",
            "de": "Fahren Sie in DiscoDrive fort, um den Zugriff auf Ihre Dateien wiederherzustellen.",
        ],
        "finder.openFailed": [
            "en": "DiscoDrive could not be opened. Please open the application manually.",
            "ru": "Не удалось открыть DiscoDrive. Пожалуйста, откройте приложение вручную.",
            "uk": "Не вдалося відкрити DiscoDrive. Будь ласка, відкрийте застосунок вручну.",
            "fr": "Impossible d’ouvrir DiscoDrive. Veuillez ouvrir l’application manuellement.",
            "es": "No se pudo abrir DiscoDrive. Abra la aplicación manualmente.",
            "sr": "Није могуће отворити DiscoDrive. Отворите апликацију ручно.",
            "de": "DiscoDrive konnte nicht geöffnet werden. Bitte öffnen Sie die App manuell.",
        ],
        "pair.title": [
            "en": "Connect to server", "ru": "Подключение к серверу",
            "uk": "Підключення до сервера", "fr": "Connexion au serveur",
            "es": "Conectar al servidor", "sr": "Повезивање на сервер",
            "de": "Mit Server verbinden",
        ],
        "pair.connect": [
            "en": "Connect", "ru": "Подключить", "uk": "Підключити",
            "fr": "Connecter", "es": "Conectar", "sr": "Повежи",
            "de": "Verbinden",
        ],
        "pair.deviceCode": [
            "en": "Device code", "ru": "Код устройства", "uk": "Код пристрою",
            "fr": "Code de l’appareil", "es": "Código del dispositivo", "sr": "Код уређаја",
            "de": "Gerätecode",
        ],
        "pair.confirmHint": [
            "en": "Confirm the device in the browser that opened, then wait…",
            "ru": "Подтвердите устройство в открывшемся браузере, затем подождите…",
            "uk": "Підтвердьте пристрій у відкритому браузері, потім зачекайте…",
            "fr": "Confirmez l’appareil dans le navigateur qui s’est ouvert, puis patientez…",
            "es": "Confirma el dispositivo en el navegador que se abrió y espera…",
            "sr": "Потврдите уређај у претраживачу који се отворио, па сачекајте…",
            "de": "Bestätigen Sie das Gerät im geöffneten Browser und warten Sie dann…",
        ],
        "pair.openManually": [
            "en": "The server sent a link that was not opened automatically. If you trust it, copy it into a browser to confirm the device:",
            "ru": "Сервер прислал ссылку, которая не была открыта автоматически. Если вы ей доверяете, скопируйте её в браузер, чтобы подтвердить устройство:",
            "uk": "Сервер надіслав посилання, яке не було відкрито автоматично. Якщо ви йому довіряєте, скопіюйте його в браузер, щоб підтвердити пристрій:",
            "fr": "Le serveur a envoyé un lien qui n’a pas été ouvert automatiquement. Si vous lui faites confiance, copiez-le dans un navigateur pour confirmer l’appareil :",
            "es": "El servidor envió un enlace que no se abrió automáticamente. Si confía en él, cópielo en un navegador para confirmar el dispositivo:",
            "sr": "Сервер је послао везу која није аутоматски отворена. Ако јој верујете, копирајте је у претраживач да бисте потврдили уређај:",
            "de": "Der Server hat einen Link gesendet, der nicht automatisch geöffnet wurde. Wenn Sie ihm vertrauen, kopieren Sie ihn in einen Browser, um das Gerät zu bestätigen:",
        ],
        // Trust dialog for a server whose certificate the system does not trust.
        "pairing.certTitle": [
            "en": "Untrusted server certificate", "ru": "Недоверенный сертификат сервера",
            "uk": "Недовірений сертифікат сервера", "fr": "Certificat du serveur non reconnu",
            "es": "Certificado del servidor no confiable", "sr": "Сертификат сервера није поуздан",
            "de": "Nicht vertrauenswürdiges Serverzertifikat",
        ],
        "pairing.certHint": [
            "en": "Only trust this if it matches the fingerprint of your server's certificate.",
            "ru": "Доверяйте, только если отпечаток совпадает с отпечатком сертификата вашего сервера.",
            "uk": "Довіряйте, лише якщо відбиток збігається з відбитком сертифіката вашого сервера.",
            "fr": "Ne faites confiance que si l’empreinte correspond à celle du certificat de votre serveur.",
            "es": "Confíe solo si coincide con la huella del certificado de su servidor.",
            "sr": "Верујте само ако се отисак поклапа са отиском сертификата вашег сервера.",
            "de": "Vertrauen Sie nur, wenn er mit dem Fingerabdruck des Zertifikats Ihres Servers übereinstimmt.",
        ],
        "pairing.certTrust": [
            "en": "Trust", "ru": "Доверять", "uk": "Довіряти", "fr": "Faire confiance",
            "es": "Confiar", "sr": "Верујем", "de": "Vertrauen",
        ],
        "pairing.certSelfSigned": [
            "en": "Self-signed", "ru": "Самоподписанный", "uk": "Самопідписаний", "fr": "Auto-signé",
            "es": "Autofirmado", "sr": "Самопотписан", "de": "Selbstsigniert",
        ],
        "pairing.certChanged": [
            "en": "The server certificate changed. If you did not replace it, someone may be intercepting the connection. Pair again to trust the new certificate.",
            "ru": "Сертификат сервера изменился. Если вы его не меняли, соединение может перехватываться. Подключите устройство заново, чтобы доверять новому сертификату.",
            "uk": "Сертифікат сервера змінився. Якщо ви його не змінювали, з’єднання можуть перехоплювати. Підключіть пристрій знову, щоб довіряти новому сертифікату.",
            "fr": "Le certificat du serveur a changé. Si vous ne l’avez pas remplacé, la connexion est peut-être interceptée. Appairez à nouveau pour faire confiance au nouveau certificat.",
            "es": "El certificado del servidor ha cambiado. Si no lo reemplazó, alguien podría estar interceptando la conexión. Vuelva a vincular para confiar en el nuevo certificado.",
            "sr": "Сертификат сервера се променио. Ако га нисте заменили, неко можда пресреће везу. Поново упарите уређај да бисте веровали новом сертификату.",
            "de": "Das Serverzertifikat hat sich geändert. Wenn Sie es nicht ersetzt haben, wird die Verbindung möglicherweise abgefangen. Koppeln Sie erneut, um dem neuen Zertifikat zu vertrauen.",
        ],
        "pairing.certHost": [
            "en": "Server", "ru": "Сервер", "uk": "Сервер", "fr": "Serveur",
            "es": "Servidor", "sr": "Сервер", "de": "Server",
        ],
        "pairing.certFingerprint": [
            "en": "SHA-256 fingerprint", "ru": "Отпечаток SHA-256", "uk": "Відбиток SHA-256",
            "fr": "Empreinte SHA-256", "es": "Huella SHA-256", "sr": "SHA-256 отисак",
            "de": "SHA-256-Fingerabdruck",
        ],
        "pairing.certSubject": [
            "en": "Issued to", "ru": "Кому выдан", "uk": "Кому видано", "fr": "Délivré à",
            "es": "Emitido para", "sr": "Издат за", "de": "Ausgestellt für",
        ],
        "pairing.certIssuer": [
            "en": "Issued by", "ru": "Кем выдан", "uk": "Ким видано", "fr": "Délivré par",
            "es": "Emitido por", "sr": "Издао", "de": "Ausgestellt von",
        ],
        "pairing.httpsRequired": [
            "en": "The server address must start with https:// (plain http:// is allowed only for this device: localhost).",
            "ru": "Адрес сервера должен начинаться с https:// (http:// допустим только для этого устройства: localhost).",
            "uk": "Адреса сервера має починатися з https:// (http:// допустимий лише для цього пристрою: localhost).",
            "fr": "L’adresse du serveur doit commencer par https:// (http:// n’est autorisé que pour cet appareil : localhost).",
            "es": "La dirección del servidor debe empezar por https:// (http:// solo se permite para este dispositivo: localhost).",
            "sr": "Адреса сервера мора почињати са https:// (http:// је дозвољен само за овај уређај: localhost).",
            "de": "Die Serveradresse muss mit https:// beginnen (http:// ist nur für dieses Gerät erlaubt: localhost).",
        ],
        "pairing.certExpires": [
            "en": "Expires", "ru": "Истекает", "uk": "Спливає", "fr": "Expire le",
            "es": "Caduca", "sr": "Истиче", "de": "Gültig bis",
        ],
        "browse.count": [
            "en": "Items", "ru": "Элементов", "uk": "Елементів",
            "fr": "Éléments", "es": "Elementos", "sr": "Ставки",
            "de": "Elemente",
        ],
        "browse.loading": ["en": "Loading the file list…", "ru": "Загружаем список файлов…", "uk": "Завантажуємо список файлів…", "de": "Dateiliste wird geladen…", "fr": "Chargement de la liste des fichiers…", "es": "Cargando la lista de archivos…", "sr": "Учитавање листе датотека…"],
        "browse.loadFailed": ["en": "Could not load the file list. Please try again.", "ru": "Не удалось загрузить список файлов. Попробуйте ещё раз.", "uk": "Не вдалося завантажити список файлів. Спробуйте ще раз.", "de": "Die Dateiliste konnte nicht geladen werden. Bitte versuchen Sie es erneut.", "fr": "Impossible de charger la liste des fichiers. Veuillez réessayer.", "es": "No se pudo cargar la lista de archivos. Vuelva a intentarlo.", "sr": "Листа датотека није учитана. Покушајте поново."],
        "browse.empty": [
            "en": "Folder is empty or not selected",
            "ru": "Папка пуста или не выбрана",
            "uk": "Папка порожня або не вибрана",
            "fr": "Dossier vide ou non sélectionné",
            "es": "Carpeta vacía o no seleccionada",
            "sr": "Фасцикла је празна или није изабрана",
            "de": "Ordner ist leer oder nicht ausgewählt",
        ],
        "menu.download": [
            "en": "Download", "ru": "Скачать", "uk": "Завантажити",
            "fr": "Télécharger", "es": "Descargar", "sr": "Преузми",
            "de": "Herunterladen",
        ],
        "ios.keepInApp": ["en": "Keep in app", "ru": "Хранить в приложении", "uk": "Зберігати в програмі", "de": "In der App behalten", "fr": "Conserver dans l’app", "es": "Conservar en la app", "sr": "Чувајте у апликацији"],
        "ios.removeFromApp": ["en": "Remove from app", "ru": "Удалить из приложения", "uk": "Видалити з програми", "de": "Aus der App entfernen", "fr": "Supprimer de l’app", "es": "Eliminar de la app", "sr": "Уклоните из апликације"],
        "menu.saveToFiles": [
            "en": "Save to Files…", "de": "In Dateien sichern…", "uk": "Зберегти у Файли…",
            "fr": "Enregistrer dans Fichiers…", "es": "Guardar en Archivos…",
            "ru": "Сохранить в Файлы…", "sr": "Сачувај у Датотеке…"
        ],
        "menu.keepLocal": [
            "en": "Keep on this Mac", "ru": "Держать локально", "uk": "Тримати локально",
            "fr": "Garder en local", "es": "Mantener local", "sr": "Чувај локално",
            "de": "Auf diesem Mac behalten",
        ],
        "menu.removeLocal": [
            "en": "Remove local copy", "ru": "Удалить локальную копию",
            "uk": "Видалити локальну копію", "fr": "Supprimer la copie locale",
            "es": "Eliminar copia local", "sr": "Уклоните локалну копију",
            "de": "Lokale Kopie entfernen",
        ],
        "toolbar.refresh": [
            "en": "Refresh", "ru": "Обновить", "uk": "Оновити",
            "fr": "Actualiser", "es": "Actualizar", "sr": "Освежи",
            "de": "Aktualisieren",
        ],
        "toolbar.free": [
            "en": "Free up space", "ru": "Освободить место", "uk": "Звільнити місце",
            "fr": "Libérer de l’espace", "es": "Liberar espacio", "sr": "Ослободи простор",
            "de": "Speicher freigeben",
        ],
        "toolbar.import": [
            "en": "Import from folder", "ru": "Импорт из папки", "uk": "Імпорт із теки",
            "fr": "Importer du dossier", "es": "Importar de carpeta", "sr": "Увези из фасцикле",
            "de": "Aus Ordner importieren",
        ],
        "toolbar.openFinder": [
            "en": "Open folder in Finder", "ru": "Открыть папку в Finder",
            "uk": "Відкрити папку у Finder", "fr": "Ouvrir le dossier dans le Finder",
            "es": "Abrir carpeta en Finder", "sr": "Отвори фасциклу у Finder-у",
            "de": "Ordner im Finder öffnen",
        ],
        "toolbar.logout": [
            "en": "Sign out", "ru": "Выйти", "uk": "Вийти",
            "fr": "Se déconnecter", "es": "Cerrar sesión", "sr": "Одјави се",
            "de": "Abmelden",
        ],
        "dialog.logoutTitle": [
            "en": "Sign out?", "ru": "Выйти?", "uk": "Вийти?",
            "fr": "Se déconnecter ?", "es": "¿Cerrar sesión?", "sr": "Одјавити се?",
            "de": "Abmelden?",
        ],
        "dialog.logoutMessage": [
            "en": "The app will be unpaired from the server. To access your files again, pair the app again.",
            "ru": "Приложение будет отвязано от сервера. Чтобы снова получить доступ к файлам, подключите его заново.",
            "uk": "Застосунок буде від’єднано від сервера. Щоб знову отримати доступ до файлів, підключіть його знову.",
            "fr": "L’application sera dissociée du serveur. Pour accéder à nouveau à vos fichiers, associez-la à nouveau.",
            "es": "La aplicación se desvinculará del servidor. Para volver a acceder a sus archivos, vincúlela de nuevo.",
            "sr": "Апликација ће бити одвојена од сервера. Да бисте поново приступили датотекама, поново је повежите.",
            "de": "Die App wird vom Server getrennt. Koppeln Sie die App erneut, um wieder auf Ihre Dateien zuzugreifen.",
        ],
        "status.updated": [
            "en": "Updated", "ru": "Обновлено", "uk": "Оновлено",
            "fr": "Mis à jour", "es": "Actualizado", "sr": "Ажурирано",
            "de": "Aktualisiert",
        ],
        "status.refreshError": [
            "en": "Update error", "ru": "Ошибка обновления", "uk": "Помилка оновлення",
            "fr": "Erreur de mise à jour", "es": "Error de actualización", "sr": "Грешка при ажурирању",
            "de": "Aktualisierungsfehler",
        ],
        "status.sessionExpired": [
            "en": "The session has expired, pair this device again", "ru": "Сессия истекла, спарьте устройство заново",
            "uk": "Сесія закінчилася, з’єднайте пристрій знову", "fr": "La session a expiré, associez à nouveau cet appareil",
            "es": "La sesión ha caducado, empareja este dispositivo de nuevo", "sr": "Сесија је истекла, поново упарите уређај",
            "de": "Die Sitzung ist abgelaufen, koppeln Sie dieses Gerät erneut",
        ],
        "status.serverError": [
            "en": "The server reported an error, try again later", "ru": "Сервер сообщил об ошибке, попробуйте позже",
            "uk": "Сервер повідомив про помилку, спробуйте пізніше", "fr": "Le serveur a signalé une erreur, réessayez plus tard",
            "es": "El servidor informó de un error, inténtalo más tarde", "sr": "Сервер је пријавио грешку, покушајте касније",
            "de": "Der Server hat einen Fehler gemeldet, versuchen Sie es später erneut",
        ],
        "status.offline": [
            "en": "Server unreachable", "ru": "Сервер недоступен", "uk": "Сервер недоступний",
            "fr": "Serveur inaccessible", "es": "Servidor inaccesible", "sr": "Сервер није доступан",
            "de": "Server nicht erreichbar",
        ],
        "status.rejected": [
            "en": "The server rejected the request", "ru": "Сервер отклонил запрос", "uk": "Сервер відхилив запит",
            "fr": "Le serveur a rejeté la requête", "es": "El servidor rechazó la solicitud", "sr": "Сервер је одбио захтев",
            "de": "Der Server hat die Anfrage abgelehnt",
        ],
        "status.opError": [
            "en": "The operation failed", "de": "Der Vorgang ist fehlgeschlagen", "uk": "Операція не вдалася",
            "fr": "L’opération a échoué", "es": "La operación falló", "ru": "Операция не удалась", "sr": "Операција није успела",
        ],
        "recovery.trashBlocked": [
            "en": "Some items could not be removed because a folder still contains files that are not in the trash. Restore or move them first.",
            "de": "Einige Objekte konnten nicht entfernt werden, weil ein Ordner noch Dateien enthält, die nicht im Papierkorb sind. Stellen Sie sie zuerst wieder her oder verschieben Sie sie.",
            "uk": "Деякі об’єкти не видалено: папка ще містить файли, яких немає в кошику. Спершу відновіть або перемістіть їх.",
            "fr": "Certains éléments n’ont pas pu être supprimés, car un dossier contient encore des fichiers qui ne sont pas dans la corbeille. Restaurez-les ou déplacez-les d’abord.",
            "es": "Algunos elementos no se pudieron eliminar porque una carpeta aún contiene archivos que no están en la papelera. Restáurelos o muévalos primero.",
            "ru": "Некоторые объекты не удалены: папка всё ещё содержит файлы, которых нет в корзине. Сначала восстановите или переместите их.",
            "sr": "Неке ставке нису уклоњене јер фасцикла још садржи датотеке које нису у отпаду. Прво их вратите или преместите.",
        ],
        "status.nodeGone": [
            "en": "This item no longer exists on the server. The list has been updated.",
            "de": "Dieses Objekt existiert nicht mehr auf dem Server. Die Liste wurde aktualisiert.",
            "uk": "Цього об’єкта більше немає на сервері. Список оновлено.",
            "fr": "Cet élément n’existe plus sur le serveur. La liste a été mise à jour.",
            "es": "Este elemento ya no existe en el servidor. La lista se ha actualizado.",
            "ru": "Этого объекта больше нет на сервере. Список обновлён.",
            "sr": "Ова ставка више не постоји на серверу. Листа је освежена.",
        ],
        "status.downloadError": [
            "en": "Download error", "ru": "Ошибка скачивания", "uk": "Помилка завантаження",
            "fr": "Erreur de téléchargement", "es": "Error de descarga", "sr": "Грешка при преузимању",
            "de": "Download-Fehler",
        ],
        "settings.title": [
            "en": "Settings", "ru": "Настройки", "uk": "Налаштування",
            "fr": "Réglages", "es": "Ajustes", "sr": "Подешавања",
            "de": "Einstellungen",
        ],
        "settings.launchAtLogin": [
            "en": "Launch at login",
            "ru": "Запускать при входе в систему",
            "uk": "Запускати під час входу в систему",
            "fr": "Lancer à l’ouverture de session",
            "es": "Iniciar al iniciar sesión",
            "sr": "Покрени при пријављивању",
            "de": "Beim Anmelden starten",
        ],
        "settings.loginApproval": [
            "en": "Please allow DiscoDrive to launch at login in System Settings.",
            "ru": "Разрешите запуск DiscoDrive при входе в системных настройках.",
            "uk": "Дозвольте запуск DiscoDrive під час входу в системних параметрах.",
            "fr": "Veuillez autoriser le lancement de DiscoDrive à l’ouverture de session dans les Réglages Système.",
            "es": "Permita que DiscoDrive se inicie al iniciar sesión en los Ajustes del Sistema.",
            "sr": "Дозволите покретање DiscoDrive при пријављивању у системским подешавањима.",
            "de": "Bitte erlauben Sie den Start von DiscoDrive beim Anmelden in den Systemeinstellungen.",
        ],
        "settings.openLoginItems": [
            "en": "Open Login Items settings",
            "ru": "Открыть настройки автозапуска",
            "uk": "Відкрити параметри автозапуску",
            "fr": "Ouvrir les réglages d’ouverture de session",
            "es": "Abrir ajustes de inicio de sesión",
            "sr": "Отвори подешавања аутоматског покретања",
            "de": "Anmeldeobjekte öffnen",
        ],
        "settings.loginError": [
            "en": "Could not change launch at login. Please try again or check Login Items in System Settings.",
            "ru": "Не удалось изменить автозапуск. Повторите попытку или проверьте объекты входа в системных настройках.",
            "uk": "Не вдалося змінити автозапуск. Спробуйте ще раз або перевірте об’єкти входу в системних параметрах.",
            "fr": "Impossible de modifier le lancement à l’ouverture de session. Réessayez ou vérifiez les éléments d’ouverture dans les Réglages Système.",
            "es": "No se pudo cambiar el inicio automático. Inténtelo de nuevo o revise los ítems de inicio en los Ajustes del Sistema.",
            "sr": "Није могуће променити аутоматско покретање. Покушајте поново или проверите ставке пријављивања у системским подешавањима.",
            "de": "Der automatische Start konnte nicht geändert werden. Versuchen Sie es erneut oder prüfen Sie die Anmeldeobjekte in den Systemeinstellungen.",
        ],
        "settings.language": [
            "en": "Language", "ru": "Язык", "uk": "Мова",
            "fr": "Langue", "es": "Idioma", "sr": "Језик",
            "de": "Sprache",
        ],
        "toolbar.newFolder": [
            "en": "New folder", "ru": "Новая папка", "uk": "Нова папка",
            "fr": "Nouveau dossier", "es": "Nueva carpeta", "sr": "Нова фасцикла",
            "de": "Neuer Ordner",
        ],
        "toolbar.addFile": [
            "en": "Add file…", "ru": "Добавить файл…", "uk": "Додати файл…",
            "fr": "Ajouter un fichier…", "es": "Añadir archivo…", "sr": "Додај датотеку…",
            "de": "Datei hinzufügen…",
        ],
        "menu.rename": [
            "en": "Rename", "ru": "Переименовать", "uk": "Перейменувати",
            "fr": "Renommer", "es": "Renombrar", "sr": "Преименуј",
            "de": "Umbenennen",
        ],
        "menu.delete": [
            "en": "Delete", "ru": "Удалить", "uk": "Видалити",
            "fr": "Supprimer", "es": "Eliminar", "sr": "Обриши",
            "de": "Löschen",
        ],
        "dialog.folderName": [
            "en": "Folder name", "ru": "Имя папки", "uk": "Назва папки",
            "fr": "Nom du dossier", "es": "Nombre de carpeta", "sr": "Назив фасцикле",
            "de": "Ordnername",
        ],
        "dialog.newName": [
            "en": "New name", "ru": "Новое имя", "uk": "Нова назва",
            "fr": "Nouveau nom", "es": "Nuevo nombre", "sr": "Нови назив",
            "de": "Neuer Name",
        ],
        "dialog.create": [
            "en": "Create", "ru": "Создать", "uk": "Створити",
            "fr": "Créer", "es": "Crear", "sr": "Направи",
            "de": "Erstellen",
        ],
        "dialog.cancel": [
            "en": "Cancel", "ru": "Отмена", "uk": "Скасувати",
            "fr": "Annuler", "es": "Cancelar", "sr": "Откажи",
            "de": "Abbrechen",
        ],
        "preview.previous": [
            "en": "Previous file", "de": "Vorherige Datei", "uk": "Попередній файл", "fr": "Fichier précédent",
            "es": "Archivo anterior", "ru": "Предыдущий файл", "sr": "Претходна датотека",
        ],
        "preview.next": [
            "en": "Next file", "de": "Nächste Datei", "uk": "Наступний файл", "fr": "Fichier suivant",
            "es": "Archivo siguiente", "ru": "Следующий файл", "sr": "Следећа датотека",
        ],
        "preview.close": [
            "en": "Close", "de": "Schließen", "uk": "Закрити", "fr": "Fermer",
            "es": "Cerrar", "ru": "Закрыть", "sr": "Затворите",
        ],
        "dialog.done": [
            "en": "Done", "ru": "Готово", "uk": "Готово",
            "fr": "Terminé", "es": "Listo", "sr": "Готово",
            "de": "Fertig",
        ],
        "status.uploadError": [
            "en": "Upload error", "ru": "Ошибка загрузки", "uk": "Помилка завантаження",
            "fr": "Erreur d’envoi", "es": "Error al subir", "sr": "Грешка при отпремању",
            "de": "Upload-Fehler",
        ],
        "vault.open": [
            "en": "Open vault", "ru": "Открыть сейф", "uk": "Відкрити сейф",
            "fr": "Ouvrir le coffre", "es": "Abrir caja fuerte", "sr": "Отворите сеф",
            "de": "Tresor öffnen",
        ],
        "vault.close": [
            "en": "Close vault", "ru": "Закрыть сейф", "uk": "Закрити сейф",
            "fr": "Fermer le coffre", "es": "Cerrar caja fuerte", "sr": "Затвори сеф",
            "de": "Tresor schließen",
        ],
        "vault.showInFinder": [
            "en": "Show in Finder", "ru": "Показать в Finder", "uk": "Показати у Finder",
            "fr": "Afficher dans le Finder", "es": "Mostrar en Finder", "sr": "Прикажи у Finder-у",
            "de": "Im Finder zeigen",
        ],
        "vault.isOpen": [
            "en": "Vault is open in Finder", "ru": "Сейф открыт в Finder", "uk": "Сейф відкрито у Finder",
            "fr": "Coffre ouvert dans le Finder", "es": "Caja fuerte abierta en Finder",
            "sr": "Сеф је отворен у Finder-у", "de": "Tresor ist im Finder geöffnet",
        ],
        "vault.unlock": [
            "en": "Unlock", "ru": "Разблокировать", "uk": "Розблокувати",
            "fr": "Déverrouiller", "es": "Desbloquear", "sr": "Откључај",
            "de": "Entsperren",
        ],
        "vault.unlockWith": [
            "en": "Unlock with %@", "ru": "Открыть по %@", "uk": "Відкрити через %@",
            "fr": "Déverrouiller avec %@", "es": "Desbloquear con %@", "sr": "Откључај помоћу %@",
            "de": "Entsperren mit %@",
        ],
        "vault.remember": [
            "en": "Remember password", "ru": "Запомнить пароль", "uk": "Запам’ятати пароль",
            "fr": "Mémoriser le mot de passe", "es": "Recordar contraseña", "sr": "Запамти лозинку",
            "de": "Passwort merken",
        ],
        "vault.unlockReason": [
            "en": "Unlock the vault", "ru": "Открыть сейф", "uk": "Відкрити сейф",
            "fr": "Déverrouiller le coffre", "es": "Abrir la caja fuerte", "sr": "Откључај сеф",
            "de": "Tresor entsperren",
        ],
        "vault.unlocking": [
            "en": "Unlocking…", "ru": "Открываю…", "uk": "Розблокування…",
            "fr": "Déverrouillage…", "es": "Desbloqueando…", "sr": "Откључавање…",
            "de": "Wird entsperrt…",
        ],
        "vault.password": [
            "en": "Vault password", "ru": "Пароль сейфа", "uk": "Пароль сейфа",
            "fr": "Mot de passe du coffre", "es": "Contraseña de la caja", "sr": "Лозинка сефа",
            "de": "Tresor-Passwort",
        ],
        "vault.wrongPassword": [
            "en": "Wrong password", "ru": "Неверный пароль", "uk": "Невірний пароль",
            "fr": "Mot de passe incorrect", "es": "Contraseña incorrecta", "sr": "Погрешна лозинка",
            "de": "Falsches Passwort",
        ],
        "vault.createVault": [
            "en": "Create vault", "ru": "Создать сейф", "uk": "Створити сейф",
            "fr": "Créer un coffre", "es": "Crear caja fuerte", "sr": "Направи сеф",
            "de": "Tresor erstellen",
        ],
        "vault.name": [
            "en": "Vault name", "ru": "Имя сейфа", "uk": "Назва сейфа",
            "fr": "Nom du coffre", "es": "Nombre de la caja", "sr": "Назив сефа",
            "de": "Tresorname",
        ],
        "vault.createError": [
            "en": "Vault creation error", "ru": "Ошибка создания сейфа", "uk": "Помилка створення сейфа",
            "fr": "Erreur de création du coffre", "es": "Error al crear la caja", "sr": "Грешка при прављењу сефа",
            "de": "Fehler beim Erstellen des Tresors",
        ],
        "quit.vaultsStillOpen": [
            "en": "Could not close the open vaults. The app will stay open. Close the vaults in Finder and try again.",
            "ru": "Не удалось закрыть открытые сейфы. Приложение продолжит работу. Закройте сейфы в Finder и повторите.",
            "uk": "Не вдалося закрити відкриті сейфи. Програма продовжить роботу. Закрийте сейфи у Finder і повторіть.",
            "fr": "Impossible de fermer les coffres ouverts. L’application restera ouverte. Fermez les coffres dans le Finder et réessayez.",
            "es": "No se pudieron cerrar las cajas abiertas. La aplicación seguirá abierta. Cierre las cajas en Finder e inténtelo de nuevo.",
            "sr": "Отворени сефови нису затворени. Апликација ће наставити да ради. Затворите сефове у Finder-у и покушајте поново.",
            "de": "Die offenen Tresore konnten nicht geschlossen werden. Die App bleibt geöffnet. Schließen Sie die Tresore im Finder und versuchen Sie es erneut.",
        ],
        "logout.domainsStillOpen": [
            "en": "Could not disconnect the Finder locations. You are still signed in. Please try again.",
            "ru": "Не удалось отключить расположения в Finder. Выход из аккаунта не выполнен. Повторите попытку.",
            "uk": "Не вдалося відключити розташування у Finder. Вихід з облікового запису не виконано. Повторіть спробу.",
            "fr": "Impossible de déconnecter les emplacements du Finder. La session reste active. Veuillez réessayer.",
            "es": "No se pudieron desconectar las ubicaciones de Finder. La sesión sigue activa. Inténtelo de nuevo.",
            "sr": "Није могуће искључити локације у Finder-у. Одјава није извршена. Покушајте поново.",
            "de": "Die Finder-Speicherorte konnten nicht getrennt werden. Sie sind weiterhin angemeldet. Bitte versuchen Sie es erneut.",
        ],
        "logout.vaultsStillOpen": [
            "en": "Could not close the open vaults; still signed in. Close them in Finder and try again.",
            "ru": "Не удалось закрыть открытые сейфы, выход не выполнен. Закройте их в Finder и повторите.",
            "uk": "Не вдалося закрити відкриті сейфи, вихід не виконано. Закрийте їх у Finder і повторіть.",
            "fr": "Impossible de fermer les coffres ouverts ; la session reste active. Fermez-les dans le Finder et réessayez.",
            "es": "No se pudieron cerrar las cajas abiertas; la sesión sigue activa. Ciérrelas en Finder e inténtelo de nuevo.",
            "sr": "Отворени сефови нису затворени, одјава није извршена. Затворите их у Finder-у и покушајте поново.",
            "de": "Die offenen Tresore konnten nicht geschlossen werden; weiterhin angemeldet. Schließen Sie sie im Finder und versuchen Sie es erneut.",
        ],
        "vault.nameTaken": [
            "en": "the name is already taken", "ru": "имя уже занято", "uk": "ім’я вже зайняте",
            "fr": "ce nom est déjà pris", "es": "el nombre ya está en uso", "sr": "назив је већ заузет",
            "de": "der Name ist bereits vergeben",
        ],
        "vault.addFile": [
            "en": "Add file", "ru": "Добавить файл", "uk": "Додати файл",
            "fr": "Ajouter un fichier", "es": "Añadir archivo", "sr": "Додај датотеку",
            "de": "Datei hinzufügen",
        ],
        "vault.recoveryTitle": [
            "en": "Recovery key", "ru": "Ключ восстановления", "uk": "Ключ відновлення",
            "fr": "Clé de récupération", "es": "Clave de recuperación", "sr": "Кључ за опоравак",
            "de": "Wiederherstellungsschlüssel",
        ],
        "vault.recoveryHint": [
            "en": "Save these words. They unlock the vault if you forget the password.",
            "ru": "Сохраните эти слова. Они откроют сейф, если забудете пароль.",
            "uk": "Збережіть ці слова. Вони відкриють сейф, якщо забудете пароль.",
            "fr": "Conservez ces mots. Ils déverrouillent le coffre en cas d’oubli du mot de passe.",
            "es": "Guarda estas palabras. Abren la caja si olvidas la contraseña.",
            "sr": "Сачувајте ове речи. Откључавају сеф ако заборавите лозинку.",
            "de": "Bewahren Sie diese Wörter auf. Sie entsperren den Tresor, falls Sie das Passwort vergessen.",
        ],
        "vault.recoverySaved": [
            "en": "I saved it", "ru": "Я сохранил", "uk": "Я зберіг",
            "fr": "Je l’ai enregistré", "es": "Lo guardé", "sr": "Сачувао сам",
            "de": "Gespeichert",
        ],
        "vault.copy": [
            "en": "Copy", "ru": "Копировать", "uk": "Копіювати",
            "fr": "Copier", "es": "Copiar", "sr": "Копирај",
            "de": "Kopieren",
        ],
        "vault.useRecovery": [
            "en": "Use recovery key", "ru": "Через ключ восстановления", "uk": "Через ключ відновлення",
            "fr": "Utiliser la clé de récupération", "es": "Usar clave de recuperación", "sr": "Користи кључ за опоравак",
            "de": "Wiederherstellungsschlüssel verwenden",
        ],
        "vault.usePassword": [
            "en": "Use password", "ru": "Через пароль", "uk": "Через пароль",
            "fr": "Utiliser le mot de passe", "es": "Usar contraseña", "sr": "Користи лозинку",
            "de": "Passwort verwenden",
        ],
        "tray.toggle": [
            "en": "Toggle window", "ru": "Показать/скрыть окно", "uk": "Показати/сховати вікно",
            "fr": "Afficher/masquer la fenêtre", "es": "Mostrar/ocultar ventana",
            "sr": "Прикажи/сакриј прозор", "de": "Fenster ein-/ausblenden",
        ],
        "tray.quit": [
            "en": "Quit DiscoDrive", "ru": "Выйти из DiscoDrive", "uk": "Вийти з DiscoDrive",
            "fr": "Quitter DiscoDrive", "es": "Salir de DiscoDrive", "sr": "Изађи из DiscoDrive-а",
            "de": "DiscoDrive beenden",
        ],
        "au.title": ["en": "Auto-upload", "ru": "Автозагрузка", "uk": "Автозавантаження", "de": "Automatischer Upload", "fr": "Envoi automatique", "es": "Subida automática", "sr": "Аутоматско отпремање"],
        "au.master": ["en": "Upload my photos", "ru": "Загружать мои фото", "uk": "Завантажувати мої фото", "de": "Meine Fotos hochladen", "fr": "Envoyer mes photos", "es": "Subir mis fotos", "sr": "Отпремај моје фотографије"],
        "au.destination": ["en": "Destination", "ru": "Куда", "uk": "Куди", "de": "Ziel", "fr": "Destination", "es": "Destino", "sr": "Одредиште"],
        "au.when": ["en": "WHEN TO UPLOAD", "ru": "КОГДА ЗАГРУЖАТЬ", "uk": "КОЛИ ЗАВАНТАЖУВАТИ", "de": "WANN HOCHLADEN", "fr": "QUAND ENVOYER", "es": "CUÁNDO SUBIR", "sr": "КАДА ОТПРЕМАТИ"],
        "au.wifi": ["en": "Wi-Fi only", "ru": "Только по Wi-Fi", "uk": "Лише через Wi-Fi", "de": "Nur über WLAN", "fr": "Wi-Fi uniquement", "es": "Solo por Wi-Fi", "sr": "Само преко Wi-Fi"],
        "au.charging": ["en": "Only while charging", "ru": "Только при зарядке", "uk": "Лише під час заряджання", "de": "Nur beim Laden", "fr": "Seulement en charge", "es": "Solo mientras se carga", "sr": "Само док се пуни"],
        "au.battery": ["en": "Not below 20% battery", "ru": "Не ниже 20% батареи", "uk": "Не нижче 20% заряду", "de": "Nicht unter 20 % Akku", "fr": "Pas sous 20 % de batterie", "es": "No por debajo del 20 % de batería", "sr": "Не испод 20% батерије"],
        "au.uploadNow": ["en": "Upload now", "ru": "Загрузить сейчас", "uk": "Завантажити зараз", "de": "Jetzt hochladen", "fr": "Envoyer maintenant", "es": "Subir ahora", "sr": "Отпреми одмах"],
        "au.log": ["en": "Log", "ru": "Журнал", "uk": "Журнал", "de": "Protokoll", "fr": "Journal", "es": "Registro", "sr": "Дневник"],
        "au.emptyLog": ["en": "Nothing uploaded yet", "ru": "Пока ничего не загружено", "uk": "Ще нічого не завантажено", "de": "Noch nichts hochgeladen", "fr": "Rien envoyé pour l’instant", "es": "Aún no se ha subido nada", "sr": "Још ништа није отпремљено"],
        "au.queued": ["en": "Waiting to upload: %1", "ru": "Ожидают загрузки: %1", "uk": "Очікують завантаження: %1", "de": "Ausstehende Uploads: %1", "fr": "Envois en attente : %1", "es": "Subidas pendientes: %1", "sr": "Чекају отпремање: %1"],
        "au.stats": ["en": "Sent %1 · skipped %2 · deferred %3", "ru": "Отправлено %1 · пропущено %2 · отложено %3", "uk": "Надіслано %1 · пропущено %2 · відкладено %3", "de": "Gesendet %1 · übersprungen %2 · zurückgestellt %3", "fr": "Envoyés %1 · ignorés %2 · reportés %3", "es": "Enviados %1 · omitidos %2 · aplazados %3", "sr": "Послато %1 · прескочено %2 · одложено %3"],
        "au.neverDeletes": ["en": "Photos stay on your phone. Auto-upload only copies them to your server.", "ru": "Фото остаются на телефоне. Автозагрузка только копирует их на сервер.", "uk": "Фото залишаються на телефоні. Автозавантаження лише копіює їх на сервер.", "de": "Fotos bleiben auf dem Telefon. Der Upload kopiert sie nur auf den Server.", "fr": "Les photos restent sur le téléphone. L’envoi ne fait que les copier sur le serveur.", "es": "Las fotos siguen en el teléfono. La subida solo las copia a tu servidor.", "sr": "Фотографије остају на телефону. Отпремање их само копира на сервер."],
        "au.background": ["en": "iOS decides when background uploads run — usually while the phone is idle and charging. Open the app to upload right away.", "ru": "iOS сама решает, когда запускать фоновую загрузку — обычно когда телефон не используется и заряжается. Откройте приложение, чтобы загрузить сразу.", "uk": "iOS сама вирішує, коли запускати фонове завантаження — зазвичай коли телефон не використовується та заряджається. Відкрийте застосунок, щоб завантажити одразу.", "de": "iOS entscheidet, wann Uploads im Hintergrund laufen — meist wenn das Telefon ungenutzt lädt. Öffne die App, um sofort hochzuladen.", "fr": "iOS décide quand les envois s’exécutent en arrière-plan — généralement quand le téléphone est inactif et en charge. Ouvrez l’app pour envoyer tout de suite.", "es": "iOS decide cuándo se ejecutan las subidas en segundo plano, normalmente con el teléfono inactivo y cargando. Abre la app para subir ahora.", "sr": "iOS одлучује када се отпремање извршава у позадини — обично док телефон мирује и пуни се. Отворите апликацију да отпремите одмах."],
        "au.blocked.wifi": ["en": "Waiting for Wi-Fi", "ru": "Ожидание Wi-Fi", "uk": "Очікування Wi-Fi", "de": "Warte auf WLAN", "fr": "En attente du Wi-Fi", "es": "Esperando Wi-Fi", "sr": "Чека се Wi-Fi"],
        "au.blocked.network": ["en": "Waiting for a connection", "ru": "Ожидание сети", "uk": "Очікування мережі", "de": "Warte auf Verbindung", "fr": "En attente de connexion", "es": "Esperando conexión", "sr": "Чека се веза"],
        "au.blocked.charging": ["en": "Waiting for the charger", "ru": "Ожидание зарядки", "uk": "Очікування зарядки", "de": "Warte auf das Ladegerät", "fr": "En attente du chargeur", "es": "Esperando el cargador", "sr": "Чека се пуњач"],
        "au.blocked.battery": ["en": "Battery too low", "ru": "Батарея разряжена", "uk": "Замало заряду", "de": "Akku zu schwach", "fr": "Batterie trop faible", "es": "Batería demasiado baja", "sr": "Батерија је прениска"],
        "au.noAccess": ["en": "DiscoDrive needs access to your photos", "ru": "Нужен доступ к фото", "uk": "Потрібен доступ до фото", "de": "Zugriff auf Fotos nötig", "fr": "Accès aux photos nécessaire", "es": "Se necesita acceso a las fotos", "sr": "Потребан је приступ фотографијама"],
        "au.backfill": ["en": "Upload existing photos too", "ru": "Загрузить и старые фото", "uk": "Завантажити й старі фото", "de": "Auch vorhandene Fotos hochladen", "fr": "Envoyer aussi les photos existantes", "es": "Subir también las fotos existentes", "sr": "Отпреми и постојеће фотографије"],
        "au.backfillAsk": ["en": "%1 photos are already on this phone and were marked as skipped. Upload them now? On a large library this takes a while and is best left on Wi-Fi and power.", "ru": "%1 фото уже есть на телефоне и помечены как пропущенные. Загрузить их сейчас? Для большой библиотеки это надолго — лучше по Wi-Fi и на зарядке.", "uk": "%1 фото вже є на телефоні й позначені як пропущені. Завантажити їх зараз? Для великої бібліотеки це надовго — краще через Wi-Fi і на зарядці.", "de": "%1 Fotos liegen bereits auf dem Telefon und wurden übersprungen. Jetzt hochladen? Bei einer großen Mediathek dauert das; am besten mit WLAN und Strom.", "fr": "%1 photos sont déjà sur ce téléphone et ont été ignorées. Les envoyer maintenant ? Sur une grande photothèque, c’est long — de préférence en Wi-Fi et branché.", "es": "%1 fotos ya están en el teléfono y se omitieron. ¿Subirlas ahora? Con una biblioteca grande lleva tiempo; mejor con Wi-Fi y cargando.", "sr": "%1 фотографија већ је на телефону и прескочене су. Отпремити их сада? Уз велику библиотеку то траје — најбоље уз Wi-Fi и пуњач."],
        "au.backfillStart": ["en": "Upload them", "ru": "Загрузить", "uk": "Завантажити", "de": "Hochladen", "fr": "Les envoyer", "es": "Subirlas", "sr": "Отпреми"],
        "au.backfillQueued": ["en": "%1 photos queued", "ru": "В очереди: %1", "uk": "У черзі: %1", "de": "%1 Fotos in der Warteschlange", "fr": "%1 photos en file", "es": "%1 fotos en cola", "sr": "У реду: %1"],
        "au.stop": ["en": "Stop", "ru": "Остановить", "uk": "Зупинити", "de": "Anhalten", "fr": "Arrêter", "es": "Detener", "sr": "Заустави"],
        "au.stopped": ["en": "Stopped. What was uploaded stays uploaded.", "ru": "Остановлено. Загруженное остаётся загруженным.", "uk": "Зупинено. Завантажене залишається завантаженим.", "de": "Angehalten. Bereits Hochgeladenes bleibt hochgeladen.", "fr": "Arrêté. Ce qui a été envoyé le reste.", "es": "Detenido. Lo ya subido permanece subido.", "sr": "Заустављено. Оно што је отпремљено остаје отпремљено."],
    ]

    // Current UI language (used by the tray menu, which is built outside SwiftUI).
    public static var currentLanguage: String {
        UserDefaults.standard.string(forKey: "ui_language") ?? "en"
    }
}
